function buildRpi2UdpReceiveModel(force)
%BUILDRPI2UDPRECEIVEMODEL Build the desktop Simulink UDP receive test model.

if nargin < 1
    force = false;
end
rootDir = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(rootDir));
setupRCCarProject;
rccar = evalin('base', 'rccar');

model = 'RPI2UdpReceiveTest';
modelFile = fullfile(rootDir, 'RPI1', 'Models', [model '.slx']);
if bdIsLoaded(model)
    close_system(model, 0);
end
if isfile(modelFile)
    if ~force
        fprintf('Keeping existing model: %s\n', modelFile);
        return
    end
    delete(modelFile);
end

new_system(model);
initCallback = [ ...
    'rccarRoot=fileparts(fileparts(fileparts(get_param(bdroot,''FileName'')))); ' ...
    'addpath(genpath(rccarRoot)); setupRCCarProject; clear rccarRoot;'];
set_param(model, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'rccar.SampleTime', ...
    'StopTime', '60', ...
    'EnablePacing', 'on', ...
    'PacingRate', '1', ...
    'InitFcn', initCallback);

load_system('instrumentlib');
receivePath = [model '/UDP Receive 80 Bytes'];
add_block('instrumentlib/UDP Receive', receivePath, ...
    'LocalAddress', '0.0.0.0', ...
    'LocalPort', num2str(rccar.Rpi2ListenPort), ...
    'Host', rccar.Rpi2Address, ...
    'Port', num2str(rccar.Rpi2SourcePort), ...
    'GetLatestData', 'on', ...
    'DataSize', '[80 1]', ...
    'DataType', 'uint8', ...
    'ByteOrder', 'little-endian', ...
    'EnableBlockingMode', 'off', ...
    'SampleTime', 'rccar.SampleTime', ...
    'Position', [55 105 205 175]);

decoderPath = [model '/Decode RPI2 Packet'];
add_block('simulink/User-Defined Functions/MATLAB Function', decoderPath, ...
    'Position', [285 70 500 220]);
chart = find(sfroot, '-isa', 'Stateflow.EMChart', 'Path', decoderPath);
chart.Script = sprintf([ ...
    'function [lane, ultrasonic, flags, sequence, frameTs, ultraTs, valid] = decode(data, status)\n' ...
    '%%#codegen\n' ...
    'persistent heldLane heldSide heldFlags heldSequence heldFrameTs heldUltraTs\n' ...
    'if isempty(heldLane)\n' ...
    '    heldLane = zeros(10,1,''single''); heldSide = single([NaN;NaN]);\n' ...
    '    heldFlags = uint8(0); heldSequence = uint32(0);\n' ...
    '    heldFrameTs = uint64(0); heldUltraTs = uint64(0);\n' ...
    'end\n' ...
    '[newLane, newSide, newFlags, newSequence, newFrameTs, newUltraTs, valid] = rpi2DecodePacket(data, status);\n' ...
    'if valid\n' ...
    '    heldLane = newLane; heldSide = newSide; heldFlags = newFlags;\n' ...
    '    heldSequence = newSequence; heldFrameTs = newFrameTs; heldUltraTs = newUltraTs;\n' ...
    'end\n' ...
    'lane = heldLane; flags = heldFlags; sequence = heldSequence;\n' ...
    'frameTs = heldFrameTs; ultraTs = heldUltraTs;\n' ...
    'ultrasonic = single([NaN; NaN; heldSide(1); heldSide(2); NaN; NaN]);\n' ...
    'end\n']);

receivePorts = get_param(receivePath, 'PortHandles');
decoderPorts = get_param(decoderPath, 'PortHandles');
add_line(model, receivePorts.Outport(1), decoderPorts.Inport(1), 'autorouting', 'on');
add_line(model, receivePorts.Outport(2), decoderPorts.Inport(2), 'autorouting', 'on');

outputNames = {'Lane Features [10]', 'Ultrasonic [6]', 'Flags', 'Sequence', ...
    'Frame Timestamp us', 'Ultrasonic Timestamp us', 'Packet Valid'};
workspaceNames = {'rpi2LaneFeatures','rpi2Ultrasonic','rpi2Flags','rpi2Sequence', ...
    'rpi2FrameTimestampUs','rpi2UltrasonicTimestampUs','rpi2PacketValid'};
for k = 1:numel(outputNames)
    y = 35 + 55 * k;
    sink = [model '/' outputNames{k}];
    add_block('simulink/Sinks/To Workspace', sink, ...
        'VariableName', workspaceNames{k}, ...
        'SaveFormat', 'Timeseries', ...
        'Position', [610 y 760 y+25]);
    sinkPorts = get_param(sink, 'PortHandles');
    add_line(model, decoderPorts.Outport(k), sinkPorts.Inport(1), 'autorouting', 'on');
end

add_block('simulink/Sinks/Display', [model '/Left Side Distance m'], ...
    'Position', [850 180 975 220]);
add_block('simulink/Sinks/Display', [model '/Right Side Distance m'], ...
    'Position', [850 245 975 285]);
add_block('simulink/Signal Routing/Demux', [model '/Split Ultrasonic'], ...
    'Outputs', '6', 'Position', [795 160 800 300]);
splitPorts = get_param([model '/Split Ultrasonic'], 'PortHandles');
leftDisplay = get_param([model '/Left Side Distance m'], 'PortHandles');
rightDisplay = get_param([model '/Right Side Distance m'], 'PortHandles');
add_line(model, decoderPorts.Outport(2), splitPorts.Inport(1), 'autorouting', 'on');
add_line(model, splitPorts.Outport(3), leftDisplay.Inport(1), 'autorouting', 'on');
add_line(model, splitPorts.Outport(4), rightDisplay.Inport(1), 'autorouting', 'on');

add_block('simulink/Sinks/Display', [model '/Packet Valid Display'], ...
    'Position', [850 350 975 390]);
validDisplay = get_param([model '/Packet Valid Display'], 'PortHandles');
add_line(model, decoderPorts.Outport(7), validDisplay.Inport(1), 'autorouting', 'on');

note = Simulink.Annotation(model, ...
    'Set rccar.Rpi2Address, start the Python sender, then run this model.');
note.Position = [50 20 760 45];
save_system(model, modelFile);
close_system(model, 0);
fprintf('Created %s\n', modelFile);
end
