function buildHpvcDesktopValidationModel(force)
%BUILDHPVCDESKTOPVALIDATIONMODEL Build the full MIDDLE UDP validation path.

if nargin < 1, force = false; end
rootDir = fileparts(mfilename('fullpath'));
addpath(genpath(rootDir));
setupRCCarProject;
rccar = evalin('base', 'rccar');

model = 'HPVCDesktopValidation';
modelFile = fullfile(rootDir, 'Models', [model '.slx']);
if ~prepareModel(model, modelFile, force, rccar), return; end

load_system('instrumentlib');
receive = [model '/UDP Receive from MIDDLE'];
add_block('instrumentlib/UDP Receive', receive, ...
    'LocalAddress', '0.0.0.0', ...
    'LocalPort', num2str(rccar.MiddleListenPort), ...
    'Host', rccar.MiddleAddress, ...
    'Port', num2str(rccar.MiddleSourcePort), ...
    'GetLatestData', 'on', ...
    'DataSize', '[156 1]', ...
    'DataType', 'uint8', ...
    'ByteOrder', 'little-endian', ...
    'EnableBlockingMode', 'off', ...
    'SampleTime', 'rccar.SampleTime', ...
    'Position', [35 75 205 145]);

add_block('simulink/Sources/Digital Clock', [model '/HPVC Local Time'], ...
    'SampleTime', 'rccar.SampleTime', 'Position', [80 205 140 225]);
add_block('simulink/Sources/Constant', [model '/Packet Timeout s'], ...
    'Value', 'rccar.PacketTimeout', 'OutDataTypeStr', 'double', ...
    'Position', [80 255 180 275]);
frontend = addReceiveFrontend(model, [285 55 520 245]);

add_block('simulink/Sources/Constant', [model '/Turn Request'], ...
    'Value', 'uint8(0)', 'OutDataTypeStr', 'uint8', ...
    'Position', [585 300 685 320]);
add_block('simulink/Sources/Constant', [model '/Vehicle Speed'], ...
    'Value', 'single(rccar.NominalSpeed)', 'OutDataTypeStr', 'single', ...
    'Position', [585 350 685 370]);
add_block('simulink/Sources/Constant', [model '/LKAS Enable'], ...
    'Value', 'true', 'OutDataTypeStr', 'boolean', ...
    'Position', [585 400 685 420]);
add_block('simulink/Ports & Subsystems/Model', [model '/HPVC Control Core'], ...
    'ModelName', 'RCCarAutonomousSystem', 'Position', [745 80 940 360]);

receivePorts = get_param(receive, 'PortHandles');
frontPorts = get_param(frontend, 'PortHandles');
corePorts = get_param([model '/HPVC Control Core'], 'PortHandles');
connect(model, receivePorts.Outport(1), frontPorts.Inport(1));
connect(model, receivePorts.Outport(2), frontPorts.Inport(2));
connect(model, get_param([model '/HPVC Local Time'], 'PortHandles').Outport(1), ...
    frontPorts.Inport(3));
connect(model, get_param([model '/Packet Timeout s'], 'PortHandles').Outport(1), ...
    frontPorts.Inport(4));
for k = 1:3
    connect(model, frontPorts.Outport(k), corePorts.Inport(k));
end
connectBlocks(model, 'Turn Request/1', 'HPVC Control Core/4');
connectBlocks(model, 'Vehicle Speed/1', 'HPVC Control Core/5');
connectBlocks(model, 'LKAS Enable/1', 'HPVC Control Core/6');

addLog(model, 'Steering Command', 'hpvcSteeringCommand', [1030 105 1185 130]);
addLog(model, 'Link Valid', 'hpvcLinkValid', [1030 170 1185 195]);
addLog(model, 'Packet Age s', 'hpvcPacketAgeS', [1030 235 1185 260]);
connectBlocks(model, 'HPVC Control Core/1', 'Steering Command/1');
connect(model, frontPorts.Outport(3), ...
    get_param([model '/Link Valid'], 'PortHandles').Inport(1));
connect(model, frontPorts.Outport(5), ...
    get_param([model '/Packet Age s'], 'PortHandles').Inport(1));

note = Simulink.Annotation(model, sprintf([ ...
    'Desktop verification only. MIDDLE -> UDP %d -> decode/CRC -> local watchdog ' ...
    '-> RCCarAutonomousSystem.'], rccar.MiddleListenPort));
note.Position = [35 20 1050 45];
save_system(model, modelFile);
close_system(model, 0);
fprintf('Created %s\n', modelFile);
end

function create = prepareModel(model, modelFile, force, rccar)
create = true;
if bdIsLoaded(model), close_system(model, 0); end
if isfile(modelFile)
    if ~force
        fprintf('Keeping existing model: %s\n', modelFile);
        create = false;
        return
    end
    delete(modelFile);
end
new_system(model);
rootExpression = [ ...
    'rccarRoot=fileparts(fileparts(get_param(bdroot,''FileName''))); ' ...
    'addpath(genpath(rccarRoot)); setupRCCarProject; clear rccarRoot;'];
set_param(model, 'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'rccar.SampleTime', 'StopTime', '60', ...
    'EnablePacing', 'on', 'PacingRate', '1', 'InitFcn', rootExpression);
end

function path = addReceiveFrontend(model, position)
path = [model '/Decode and Monitor MIDDLE'];
add_block('simulink/User-Defined Functions/MATLAB Function', path, ...
    'Position', position);
chart = find(sfroot, '-isa', 'Stateflow.EMChart', 'Path', path);
chart.Script = frontendScript();
setChartData(chart, 'data', 'uint8', '[156 1]');
setChartData(chart, 'receiveStatus', 'boolean', '1');
setChartData(chart, 'localTimeS', 'double', '1');
setChartData(chart, 'timeoutS', 'double', '1');
setChartData(chart, 'lane', 'single', '[10 1]');
setChartData(chart, 'ultrasonic', 'single', '[6 1]');
setChartData(chart, 'controlValid', 'boolean', '1');
setChartData(chart, 'sequence', 'uint32', '1');
    setChartData(chart, 'ageS', 'double', '1');
    setChartData(chart, 'flags', 'uint8', '1');
    setChartData(chart, 'packetValid', 'boolean', '1');
    setChartData(chart, 'linkValid', 'boolean', '1');
end

function setChartData(chart, name, dataType, sizeExpression)
item = find(chart, '-isa', 'Stateflow.Data', 'Name', name);
assert(isscalar(item), 'Could not find MATLAB Function data item: %s', name);
item.DataType = dataType;
item.Props.Array.Size = sizeExpression;
end

function script = frontendScript()
script = sprintf([ ...
    'function [lane, ultrasonic, controlValid, sequence, ageS, flags, packetValid, linkValid] = frontend(data, receiveStatus, localTimeS, timeoutS)\n' ...
    '%%#codegen\n' ...
    'persistent heldLane heldSide heldFlags heldSequence\n' ...
    'if isempty(heldLane)\n' ...
    ' heldLane=zeros(10,1,''single''); heldSide=single([NaN;NaN]);\n' ...
    ' heldFlags=uint8(0); heldSequence=uint32(0);\n' ...
    'end\n' ...
    '[newLane,newSide,newFlags,newSequence,~,~,packetValid]=middleDecodePacket(data,receiveStatus);\n' ...
    'if packetValid\n' ...
    ' heldLane=newLane; heldSide=newSide; heldFlags=newFlags; heldSequence=newSequence;\n' ...
    'end\n' ...
    '[linkValid,ageS,~]=middleLinkMonitor(localTimeS,packetValid,newSequence,timeoutS,false);\n' ...
    'cameraValid=bitand(heldFlags,uint8(1))~=0; laneValid=bitand(heldFlags,uint8(2))~=0;\n' ...
    'controlValid=linkValid && cameraValid && laneValid;\n' ...
    'lane=heldLane; ultrasonic=single([NaN;NaN;heldSide(1);heldSide(2);NaN;NaN]);\n' ...
    'sequence=heldSequence; flags=heldFlags;\n' ...
    'end\n']);
end

function addLog(model, blockName, variableName, position)
add_block('simulink/Sinks/To Workspace', [model '/' blockName], ...
    'VariableName', variableName, 'SaveFormat', 'Timeseries', ...
    'Position', position);
end

function connectBlocks(model, source, destination)
add_line(model, source, destination, 'autorouting', 'on');
end

function connect(model, sourceHandle, destinationHandle)
add_line(model, sourceHandle, destinationHandle, 'autorouting', 'on');
end
